"use client";
import { useEffect,useState } from "react";
import { Buildings,ChartLineUp,ShoppingCart,TrendUp,UsersThree,WarningCircle } from "@phosphor-icons/react";
import { AdminShell } from "@/components/admin-shell";
import { apiRequest,ApiRequestError } from "@/lib/api";
import { useAdminSession } from "@/lib/use-admin-session";
type Dashboard={metrics:{active_clients:number;pending_applications:number;active_orders:number;month_revenue_rwf:string};monthlyRevenue:{label:string;revenue_rwf:string}[]};
const money=(value:string)=>new Intl.NumberFormat("en-RW",{style:"currency",currency:"RWF",maximumFractionDigits:0}).format(Number(value));
export default function AnalyticsPage(){const{user,token,logout}=useAdminSession();const[data,setData]=useState<Dashboard|null>(null);const[error,setError]=useState("");useEffect(()=>{if(!token)return;apiRequest<{data:Dashboard}>("/api/v1/admin/dashboard",{headers:{Authorization:`Bearer ${token}`}}).then(result=>setData(result.data)).catch(cause=>setError(cause instanceof ApiRequestError?cause.message:"Analytics could not be loaded."))},[token]);const total=data?.monthlyRevenue.reduce((sum,item)=>sum+Number(item.revenue_rwf),0)||0;const max=Math.max(...(data?.monthlyRevenue.map(item=>Number(item.revenue_rwf))||[0]),1);return <AdminShell user={user} active="analytics" onLogout={logout}><section className="admin-content"><div className="admin-title"><div><h2>Business analytics</h2><p>Commercial performance and partner conversion indicators.</p></div><button>Last 6 months</button></div>{error&&<div className="admin-error"><WarningCircle/>{error}</div>}<div className="analytics-kpis"><article><span><ChartLineUp/></span><small>Six-month order value</small><strong>{money(String(total))}</strong><em><TrendUp/> Rolling performance</em></article><article><span><Buildings/></span><small>Approved clients</small><strong>{data?.metrics.active_clients??"—"}</strong><em>Verified accounts</em></article><article><span><UsersThree/></span><small>Applications pending</small><strong>{data?.metrics.pending_applications??"—"}</strong><em>Conversion opportunity</em></article><article><span><ShoppingCart/></span><small>Orders in progress</small><strong>{data?.metrics.active_orders??"—"}</strong><em>Fulfilment pipeline</em></article></div><section className="dashboard-card analytics-chart"><header><div><h2>Monthly order value</h2><p>Revenue represented by submitted wholesale orders</p></div><b>{money(data?.metrics.month_revenue_rwf||"0")} this month</b></header><div className="large-bars">{data?.monthlyRevenue.map(item=><div key={item.label}><span style={{height:`${Math.max(5,Number(item.revenue_rwf)/max*100)}%`}}><i>{Number(item.revenue_rwf)?money(item.revenue_rwf):""}</i></span><small>{item.label}</small></div>)}</div></section></section></AdminShell>}
