"use client";
import { useEffect,useMemo,useState } from "react";
import { Buildings,MagnifyingGlass,ShoppingCart,UsersThree,Wallet,WarningCircle } from "@phosphor-icons/react";
import { AdminShell } from "@/components/admin-shell";
import { apiRequest,ApiRequestError } from "@/lib/api";
import { useAdminSession } from "@/lib/use-admin-session";
type Client={id:string;name:string;type:string;registration_number:string;tin:string;district:string;country:string;status:"APPROVED"|"SUSPENDED";credit_limit_rwf:string;payment_terms_days:number;approved_at:string|null;contact:{fullName:string;email:string;phone:string;jobTitle:string};order_count:number;lifetime_value_rwf:string};
const money=(value:string|number)=>new Intl.NumberFormat("en-RW",{style:"currency",currency:"RWF",maximumFractionDigits:0}).format(Number(value));
export default function ClientsPage(){const{user,token,logout}=useAdminSession();const[clients,setClients]=useState<Client[]>([]);const[search,setSearch]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");useEffect(()=>{if(!token)return;apiRequest<{data:Client[]}>("/api/v1/admin/clients",{headers:{Authorization:`Bearer ${token}`}}).then(result=>setClients(result.data)).catch(cause=>setError(cause instanceof ApiRequestError?cause.message:"Clients could not be loaded.")).finally(()=>setLoading(false))},[token]);const visible=useMemo(()=>clients.filter(item=>`${item.name} ${item.contact.fullName} ${item.contact.email} ${item.tin}`.toLowerCase().includes(search.toLowerCase())),[clients,search]);const totalValue=clients.reduce((sum,item)=>sum+Number(item.lifetime_value_rwf),0);return <AdminShell user={user} active="clients" onLogout={logout}><section className="admin-content"><div className="admin-title"><div><h2>Wholesale clients</h2><p>Approved business accounts, contacts and commercial activity.</p></div></div>{error&&<div className="admin-error"><WarningCircle/>{error}</div>}<div className="metric-grid metric-three"><article><span className="green"><UsersThree/></span><div><small>Active clients</small><strong>{clients.filter(item=>item.status==="APPROVED").length}</strong></div></article><article><span className="amber"><ShoppingCart/></span><div><small>Total orders</small><strong>{clients.reduce((sum,item)=>sum+item.order_count,0)}</strong></div></article><article><span className="blue"><Wallet/></span><div><small>Lifetime order value</small><strong className="metric-money">{money(totalValue)}</strong></div></article></div><section className="applications"><div className="table-tools"><b className="table-title">Client directory</b><label><MagnifyingGlass/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search clients"/></label></div><div className="data-card-grid">{loading?<div className="empty-state">Loading clients…</div>:visible.length===0?<div className="empty-state">No approved clients yet.</div>:visible.map(client=><article className="client-card" key={client.id}><div className="client-card-head"><span><Buildings/></span><i className={`status ${client.status.toLowerCase()}`}>{client.status}</i></div><h3>{client.name}</h3><small>{client.type.replaceAll("_"," ")} · {client.district}</small><dl><div><dt>Contact</dt><dd>{client.contact.fullName}</dd></div><div><dt>Email</dt><dd>{client.contact.email}</dd></div><div><dt>Orders</dt><dd>{client.order_count}</dd></div><div><dt>Order value</dt><dd>{money(client.lifetime_value_rwf)}</dd></div><div><dt>Payment terms</dt><dd>{client.payment_terms_days} days</dd></div><div><dt>Credit limit</dt><dd>{money(client.credit_limit_rwf)}</dd></div></dl><a href={`mailto:${client.contact.email}`}>Contact client →</a></article>)}</div></section></section></AdminShell>}
