"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { Bell,Buildings,CheckCircle,Clock,FileText,MagnifyingGlass,Package,SignOut,Storefront,UsersThree,WarningCircle,XCircle } from "@phosphor-icons/react";
import { apiRequest,ApiRequestError } from "@/lib/api";
import { AuthUser,readSession } from "@/lib/session";

type Status="PENDING"|"APPROVED"|"SUSPENDED"|"REJECTED";
type Registration={id:string;name:string;type:string;registration_number:string;tin:string;pharmacy_licence_number:string|null;operating_licence_number:string;district:string;country:string;status:Status;created_at:string;contact:{id:string;fullName:string;email:string;phone:string;jobTitle:string}};
const statuses:Status[]=["PENDING","APPROVED","SUSPENDED","REJECTED"];
const staffRoles=["SUPER_ADMIN","SALES_MANAGER"];

export default function AdminPage(){
 const router=useRouter();const[user,setUser]=useState<AuthUser|null>(null);const[token,setToken]=useState("");const[records,setRecords]=useState<Registration[]>([]);const[filter,setFilter]=useState<Status|"ALL">("PENDING");const[query,setQuery]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[selected,setSelected]=useState<Registration|null>(null);const[reason,setReason]=useState("");const[updating,setUpdating]=useState(false);
 const load=useCallback(async(accessToken:string)=>{setLoading(true);setError("");try{const responses=await Promise.all(statuses.map(status=>apiRequest<{data:Registration[]}>(`/api/v1/admin/registrations?status=${status}`,{headers:{Authorization:`Bearer ${accessToken}`}})));setRecords(responses.flatMap(item=>item.data))}catch(cause){setError(cause instanceof ApiRequestError?cause.message:"Dashboard data could not be loaded.")}finally{setLoading(false)}},[]);
 useEffect(()=>{const session=readSession();if(!session||!staffRoles.includes(session.user.role)){router.replace("/login");return}setUser(session.user);setToken(session.accessToken);load(session.accessToken)},[load,router]);
 const visible=useMemo(()=>records.filter(item=>(filter==="ALL"||item.status===filter)&&(`${item.name} ${item.contact.fullName} ${item.contact.email} ${item.tin}`.toLowerCase().includes(query.toLowerCase()))),[records,filter,query]);
 const count=(status:Status)=>records.filter(item=>item.status===status).length;
 async function changeStatus(status:Status){if(!selected)return;if((status==="REJECTED"||status==="SUSPENDED")&&!reason.trim()){setError("Please enter a reason before restricting this account.");return}setUpdating(true);setError("");try{await apiRequest(`/api/v1/admin/registrations/${selected.id}/status`,{method:"PATCH",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({status,reason:reason.trim()||undefined})});setSelected(null);setReason("");await load(token)}catch(cause){setError(cause instanceof ApiRequestError?cause.message:"The account could not be updated.")}finally{setUpdating(false)}}
 function logout(){localStorage.removeItem("flr_access_token");localStorage.removeItem("flr_user");sessionStorage.removeItem("flr_access_token");sessionStorage.removeItem("flr_user");router.replace("/login")}
 if(!user)return <main className="portal-loading"><Clock size={28}/><p>Verifying staff access…</p></main>;
 return <div className="admin-shell"><aside className="admin-sidebar"><div className="admin-brand"><b>FLR</b><span>ADMIN PORTAL</span></div><nav><a className="active"><Storefront/>Dashboard</a><a><UsersThree/>Applications <em>{count("PENDING")}</em></a><a><Buildings/>Clients</a><a><Package/>Catalogue</a><a><FileText/>Orders</a></nav><button onClick={logout}><SignOut/>Sign out</button></aside><main className="admin-main"><header><div><span>Administration</span><h1>Good day, {user.fullName.split(" ")[0]}</h1></div><div className="admin-profile"><button aria-label="Notifications"><Bell/></button><i>{user.fullName.split(" ").map(part=>part[0]).slice(0,2).join("")}</i><span><b>{user.fullName}</b><small>{user.role.replaceAll("_"," ")}</small></span></div></header>
 <section className="admin-content"><div className="admin-title"><div><h2>Partner applications</h2><p>Review and manage wholesale account requests.</p></div><button onClick={()=>load(token)}>Refresh data</button></div>{error&&<div className="admin-error"><WarningCircle/>{error}</div>}<div className="metric-grid"><article><span className="amber"><Clock/></span><div><small>Pending review</small><strong>{count("PENDING")}</strong></div></article><article><span className="green"><CheckCircle/></span><div><small>Approved clients</small><strong>{count("APPROVED")}</strong></div></article><article><span className="red"><XCircle/></span><div><small>Rejected</small><strong>{count("REJECTED")}</strong></div></article><article><span className="blue"><UsersThree/></span><div><small>Total applications</small><strong>{records.length}</strong></div></article></div>
 <section className="applications"><div className="table-tools"><div className="status-tabs"><button className={filter==="ALL"?"active":""} onClick={()=>setFilter("ALL")}>All</button>{statuses.map(status=><button key={status} className={filter===status?"active":""} onClick={()=>setFilter(status)}>{status.toLowerCase()} <b>{count(status)}</b></button>)}</div><label><MagnifyingGlass/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search company, contact or TIN"/></label></div><div className="admin-table"><div className="table-row table-head"><span>Business</span><span>Contact</span><span>Location</span><span>Submitted</span><span>Status</span><span></span></div>{loading?<div className="empty-state">Loading applications…</div>:visible.length===0?<div className="empty-state">No applications match this view.</div>:visible.map(item=><button className="table-row" key={item.id} onClick={()=>{setSelected(item);setReason("")}}><span><b>{item.name}</b><small>{item.type.replaceAll("_"," ")} · TIN {item.tin}</small></span><span><b>{item.contact.fullName}</b><small>{item.contact.email}</small></span><span><b>{item.district}</b><small>{item.country}</small></span><span><b>{new Intl.DateTimeFormat("en-RW",{dateStyle:"medium"}).format(new Date(item.created_at))}</b><small>{item.contact.phone}</small></span><span><i className={`status ${item.status.toLowerCase()}`}>{item.status}</i></span><span className="review-link">Review →</span></button>)}</div></section></section></main>
 {selected&&<div className="review-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setSelected(null)}}><aside className="review-panel"><button className="close-review" onClick={()=>setSelected(null)}>×</button><span className="review-eyebrow">Application review</span><h2>{selected.name}</h2><i className={`status ${selected.status.toLowerCase()}`}>{selected.status}</i><div className="review-grid"><label>Business type<b>{selected.type.replaceAll("_"," ")}</b></label><label>Registration no.<b>{selected.registration_number}</b></label><label>TIN<b>{selected.tin}</b></label><label>Operating licence<b>{selected.operating_licence_number}</b></label><label>District<b>{selected.district}, {selected.country}</b></label><label>Pharmacy licence<b>{selected.pharmacy_licence_number||"Not supplied"}</b></label></div><h3>Primary contact</h3><div className="contact-card"><b>{selected.contact.fullName}</b><span>{selected.contact.jobTitle}</span><a href={`mailto:${selected.contact.email}`}>{selected.contact.email}</a><a href={`tel:${selected.contact.phone}`}>{selected.contact.phone}</a></div><label className="decision-reason">Decision note<textarea value={reason} onChange={event=>setReason(event.target.value)} placeholder="Required when rejecting or suspending an account" maxLength={500}/></label><div className="decision-actions"><button disabled={updating} className="approve" onClick={()=>changeStatus("APPROVED")}><CheckCircle/>Approve</button><button disabled={updating} className="suspend" onClick={()=>changeStatus("SUSPENDED")}>Suspend</button><button disabled={updating} className="reject" onClick={()=>changeStatus("REJECTED")}><XCircle/>Reject</button></div></aside></div>}
 </div>
}
