"use client";
import Link from "next/link";
import { ArrowLeft, CheckCircle, FileArrowUp } from "@phosphor-icons/react";
import { FormEvent, useState } from "react";

export default function RegisterPage(){const [submitted,setSubmitted]=useState(false);function submit(event:FormEvent){event.preventDefault();setSubmitted(true)}if(submitted)return <main className="registration-success"><CheckCircle/><h1>Registration request received</h1><p>This prototype has validated the required fields. Backend submission and reference generation will be connected in the secure portal phase.</p><Link href="/">Return home</Link></main>;return <main className="register-page"><header><div className="container"><Link href="/"><ArrowLeft/> Back to website</Link><b>FLR Ltd.<small>Partner Registration</small></b><Link href="/login">Already registered? Login</Link></div></header><div className="registration-heading container"><span>B2B client portal</span><h1>Register your business</h1><p>Apply for access to wholesale pricing and online ordering. Fields marked <strong>*</strong> are required.</p></div><form className="registration-form container" onSubmit={submit}>
<fieldset><legend><span>01</span> Business Information</legend><div className="form-grid"><label>Business / Company Name *<input required/></label><label>Business Type *<select required defaultValue=""><option value="" disabled>Select business type</option><option>Pharmacy</option><option>Clinic / Hospital</option><option>Beauty Retailer</option><option>Supermarket</option><option>Wholesale Buyer</option><option>Other</option></select></label><label>Business Registration Number *<input required/></label><label>TIN Number *<input required inputMode="numeric"/></label><label>Pharmacy Licence Number<input placeholder="Required for pharmacies; otherwise N/A"/></label><label>Business Operating Licence *<input required/></label><label>VAT Registration Number<input/></label><label>Street Address *<input required/></label><label>District *<select required defaultValue=""><option value="" disabled>Select district</option><option>Gasabo</option><option>Kicukiro</option><option>Nyarugenge</option><option>Other Rwanda District</option></select></label><label>Country *<select required defaultValue="Rwanda"><option>Rwanda</option><option>Burundi</option><option>DR Congo</option><option>Kenya</option><option>Tanzania</option><option>Uganda</option></select></label></div></fieldset>
<fieldset><legend><span>02</span> Contact Person</legend><div className="form-grid"><label>Full Name *<input required/></label><label>Job Title / Role *<input required/></label><label>Professional Licence Number<input placeholder="Required for pharmacists"/></label><label>Business Email Address *<input type="email" required/></label><label>Primary Phone Number *<input type="tel" required placeholder="+250"/></label><label>WhatsApp Number<input type="tel" placeholder="+250"/></label></div></fieldset>
<fieldset><legend><span>03</span> Account Security</legend><div className="form-grid"><label>Password *<input type="password" required minLength={8} pattern="(?=.*[A-Z])(?=.*[0-9])(?=.*[^A-Za-z0-9]).{8,}" title="At least 8 characters with an uppercase letter, number and symbol"/></label><label>Confirm Password *<input type="password" required minLength={8}/></label></div><p className="field-help">Minimum 8 characters including an uppercase letter, number and symbol.</p></fieldset>
<fieldset><legend><span>04</span> Supporting Documents</legend><p className="field-help">PDF, JPG or PNG. Secure storage and virus scanning will be connected with the backend.</p><div className="upload-grid">{["Business Registration Certificate *","TIN Certificate / RRA Document *","Pharmacy Licence (if applicable)","Operating Licence *","National ID / Passport *"].map((name)=><label key={name}><FileArrowUp/><span>{name}</span><input type="file" accept=".pdf,.jpg,.jpeg,.png" required={name.endsWith("*")}/></label>)}</div></fieldset>
<fieldset><legend><span>05</span> Consent</legend><div className="consents"><label><input type="checkbox" required/> I accept the FLR Ltd. wholesale Terms & Conditions. *</label><label><input type="checkbox" required/> I accept the Privacy Policy and data processing terms. *</label><label><input type="checkbox" required/> I understand that wholesale pricing is confidential. *</label></div></fieldset><button className="submit-registration" type="submit">Submit Registration Request</button><p className="submission-note">Applications are reviewed within 24–48 business hours after backend verification is activated.</p></form></main>}
