"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent,useState } from "react";
import { ArrowLeft,Eye,EyeSlash,LockKey } from "@phosphor-icons/react";
import { apiRequest,ApiRequestError } from "@/lib/api";
import { AuthUser,saveSession } from "@/lib/session";
type LoginResponse={accessToken:string;user:AuthUser};
export default function LoginPage(){
 const router=useRouter();const[error,setError]=useState("");const[loading,setLoading]=useState(false);const[visible,setVisible]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");setLoading(true);const form=new FormData(event.currentTarget);try{const result=await apiRequest<LoginResponse>("/api/v1/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:form.get("email"),password:form.get("password")})});saveSession(result.accessToken,result.user,form.get("remember")==="on");router.push(result.user.role==="CLIENT"?"/wholesale-preview":"/admin/overview")}catch(cause){setError(cause instanceof ApiRequestError?cause.message:"Login failed. Please try again.")}finally{setLoading(false)}}
 return <main className="auth-page"><section className="auth-aside"><Link href="/"><ArrowLeft/>Back to website</Link><div><span>FLR Ltd.</span><h1>Your wholesale portal, always available.</h1><p>Secure access to wholesale operations, verified clients, orders and inventory.</p></div><small>Pharmaceutical Wholesale · Dépôt Pharmaceutique</small></section><section className="auth-panel"><form className="auth-form" onSubmit={submit}><div className="auth-logo">FLR</div><span>Secure portal access</span><h2>Welcome back</h2><p>Sign in with your approved client or FLR staff account.</p>{error&&<div className="form-error" role="alert">{error}</div>}<label>Business email<input name="email" type="email" required autoComplete="email" placeholder="name@company.com" disabled={loading}/></label><label>Password<div className="password-field"><input name="password" type={visible?"text":"password"} required minLength={8} autoComplete="current-password" placeholder="Your password" disabled={loading}/><button type="button" onClick={()=>setVisible(value=>!value)} aria-label={visible?"Hide password":"Show password"}>{visible?<EyeSlash/>:<Eye/>}</button></div></label><div className="form-row"><label className="check"><input name="remember" type="checkbox" disabled={loading}/>Remember me</label><span>Contact FLR support for access help.</span></div><button type="submit" disabled={loading}>{loading?"Signing in…":"Login to your account"}</button><div className="secure-note"><LockKey/>Encrypted, role-protected access</div><p className="auth-switch">Not registered? <Link href="/register">Create a partner account</Link></p></form></section></main>;
}
