"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent,useState } from "react";
import { ArrowLeft,LockKey } from "@phosphor-icons/react";
import { apiRequest,ApiRequestError } from "@/lib/api";
import { AuthUser,saveSession } from "@/lib/session";

type LoginResponse={accessToken:string;user:AuthUser};
export default function LoginPage(){const router=useRouter();const[error,setError]=useState("");const[loading,setLoading]=useState(false);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setError("");setLoading(true);const form=new FormData(event.currentTarget);try{const result=await apiRequest<LoginResponse>("/api/v1/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:form.get("email"),password:form.get("password")})});saveSession(result.accessToken,result.user,form.get("remember")==="on");router.push(result.user.role==="CLIENT"?"/wholesale-preview":"/admin")}catch(cause){setError(cause instanceof ApiRequestError?cause.message:"Login failed. Please try again.")}finally{setLoading(false)}}return <main className="auth-page"><section className="auth-aside"><Link href="/"><ArrowLeft/> Back to website</Link><div><span>FLR Ltd.</span><h1>Your wholesale portal, always available.</h1><p>Access approved pricing, stock availability, orders, invoices and partner documents.</p></div></section><section className="auth-panel"><form className="auth-form" onSubmit={submit}><div className="auth-logo">FLR</div><span>Verified client access</span><h2>Login to your account</h2><p>Wholesale access is available to approved FLR business clients and staff.</p>{error&&<div className="form-error" role="alert">{error}</div>}<label>Business email<input name="email" type="email" required autoComplete="email" placeholder="name@company.com" disabled={loading}/></label><label>Password<input name="password" type="password" required minLength={8} autoComplete="current-password" placeholder="Your password" disabled={loading}/></label><div className="form-row"><label className="check"><input name="remember" type="checkbox" disabled={loading}/> Remember me</label><span>Contact FLR support for access help.</span></div><button type="submit" disabled={loading}>{loading?"Signing in…":"Login to Your Account"}</button><div className="secure-note"><LockKey/> Secure, encrypted client access</div><p className="auth-switch">Not registered? <Link href="/register">Create a partner account</Link></p></form></section></main>}
