"use client";
import { useEffect,useMemo,useState } from "react";
import { MagnifyingGlass,Package,Stack,Tag,WarningCircle } from "@phosphor-icons/react";
import { AdminShell } from "@/components/admin-shell";
import { apiRequest,ApiRequestError } from "@/lib/api";
import { useAdminSession } from "@/lib/use-admin-session";
type Product={id:string;sku:string;name:string;size:string;unit_price_rwf:string;minimum_order_quantity:number;case_size:number;stock_quantity:number;stock_status:string;brand_name:string;brand_slug:string};type Brand={id:string;slug:string;name:string;category:string};
const money=(value:string)=>new Intl.NumberFormat("en-RW",{style:"currency",currency:"RWF",maximumFractionDigits:0}).format(Number(value));
export default function CataloguePage(){const{user,token,logout}=useAdminSession();const[products,setProducts]=useState<Product[]>([]);const[brands,setBrands]=useState<Brand[]>([]);const[search,setSearch]=useState("");const[brand,setBrand]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");useEffect(()=>{if(!token)return;Promise.all([apiRequest<{data:Product[]}>("/api/v1/catalog/wholesale/products?limit=100",{headers:{Authorization:`Bearer ${token}`}}),apiRequest<{data:Brand[]}>("/api/v1/catalog/brands")]).then(([productResult,brandResult])=>{setProducts(productResult.data);setBrands(brandResult.data)}).catch(cause=>setError(cause instanceof ApiRequestError?cause.message:"Catalogue could not be loaded.")).finally(()=>setLoading(false))},[token]);const visible=useMemo(()=>products.filter(item=>(!brand||item.brand_slug===brand)&&`${item.name} ${item.brand_name} ${item.sku}`.toLowerCase().includes(search.toLowerCase())),[products,brand,search]);return <AdminShell user={user} active="catalogue" onLogout={logout}><section className="admin-content"><div className="admin-title"><div><h2>Product catalogue</h2><p>Wholesale products, prices and current inventory.</p></div></div>{error&&<div className="admin-error"><WarningCircle/>{error}</div>}<div className="metric-grid metric-three"><article><span className="green"><Package/></span><div><small>Products</small><strong>{products.length}</strong></div></article><article><span className="blue"><Tag/></span><div><small>Active brands</small><strong>{brands.length}</strong></div></article><article><span className="amber"><Stack/></span><div><small>Units in stock</small><strong>{products.reduce((sum,item)=>sum+item.stock_quantity,0)}</strong></div></article></div><section className="applications"><div className="table-tools"><select value={brand} onChange={event=>setBrand(event.target.value)}><option value="">All brands</option>{brands.map(item=><option value={item.slug} key={item.id}>{item.name}</option>)}</select><label><MagnifyingGlass/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search product, brand or SKU"/></label></div><div className="catalogue-table"><div className="catalogue-row catalogue-head"><span>Product</span><span>Brand</span><span>Price</span><span>MOQ / Case</span><span>Stock</span></div>{loading?<div className="empty-state">Loading catalogue…</div>:visible.length===0?<div className="empty-state">No products have been added yet.</div>:visible.map(item=><article className="catalogue-row" key={item.id}><span><b>{item.name}</b><small>{item.sku} · {item.size}</small></span><span>{item.brand_name}</span><span><b>{money(item.unit_price_rwf)}</b></span><span>{item.minimum_order_quantity} / {item.case_size}</span><span><i className={`stock ${item.stock_status.toLowerCase()}`}>{item.stock_status.replaceAll("_"," ")}</i><small>{item.stock_quantity} units</small></span></article>)}</div></section></section></AdminShell>}
